### ISSUE TITLE
CarouselView inside TabbedPage

### ISSUE THREAD

**Issue by rredoh** [AndreiMisiukevich/CardView#109]
Hi Andrei. Could you please make your carouselview working inside TabbedPage? I read everywhere there's conflict with swiping gesture but not found any fix. Thank you very much and keep up the good work :D

**Comment by AndreiMisiukevich** [comment]
@rredoh Hi
I think, you will have to disable tabbedPage's swiping 
https://forums.xamarin.com/discussion/81092/disable-swipe-on-tabbed-page

**Comment by rredoh** [comment]
Thanks for the suggestion @AndreiMisiukevich , but do we have another choice?

**Comment by AndreiMisiukevich** [comment]
@rredoh hm, i don't see any solution
How can we distinguish card swipes and page swipes ?)

**Comment by rredoh** [comment]
Ah I see. Thanks for the help then :)

But I have seen some apps can have this carousel and swiping tabbedpage. Just curious

**Comment by logicsandbox** [comment]
@AndreiMisiukevich Sorry to bring up this old issue. In our testing, the issue is not distinguishing between CarouselView swipes and Tab swipes, but rather that the CarouselView swipes seem to stop registering after 5-10px of swiping. After that, the swipe action is completed automatically, without the user lifting their finger. 

If you swipe in a diagonal motion (I saw something in the code that was checking delta Y when determining if the touch counts), then this does not happen, and the user can swipe back and forth by holding on to the card, without the ItemSwiped event ever firing (until they let go).

I have experimented with all of these properties but cannot get this behavior to change:

- MoveDistance
- MoveWidthPercentage
- MoveThresholdDistance
- SwipeThresholdDistance
- SwipeThresholdTime
- Creating a base class of PanCardView.Droid/CardsViewRenderer.cs with SwipeThreshold set higher

Do you have any advice? Am I doing something incorrectly?

**Comment by AndreiMisiukevich** [comment]
@logicsandbox hi
could you please provide small sample and, maybe, video?

Also, try to set **IsPanInteractionEnabled = false**

**Comment by logicsandbox** [comment]
@AndreiMisiukevich Here is a video: https://youtu.be/I3oW44nWZXg

This video was recorded without trying your IsPanInteractionEnabled = false, but enabling it did not seem to change anything.

I've attached a zip of the app in the video. I will make a GitHub repo out of it when I get home from work (8 hours from now at least).

[TestApp.zip](https://github.com/AndreiMisiukevich/CardView/files/2812924/TestApp.zip)

**Comment by logicsandbox** [comment]
> https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView.Droid/CardsViewRenderer.cs
> 
> If somebody wants to debug :)

@AndreiMisiukevich I was having trouble getting the solution to build because the Droid and iOS projects are not part of the solution. Are there instructions anywhere?

**Comment by AndreiMisiukevich** [comment]
@logicsandbox sorry, what do you mean?

![image](https://user-images.githubusercontent.com/10124814/51988269-57aac280-24b5-11e9-8529-5eecc01269d4.png)

**Comment by logicsandbox** [comment]
@AndreiMisiukevich https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/PanCardView.sln Only has the one project in it?

**Comment by AndreiMisiukevich** [comment]
@logicsandbox if you want you can make a PR (remove that file)

**Comment by logicsandbox** [comment]
> @logicsandbox but it's so strange, that iphone has the same behavior.. i will try on simulator

@AndreiMisiukevich I just tried on an iPad and the swiping seems to work fine. This may be only an Android issue.

**Comment by AndreiMisiukevich** [comment]
@logicsandbox i think there is only one solution for now -- disable tabbedPage scrolling :(

**Comment by AndreiMisiukevich** [comment]
@logicsandbox hm.. i think yes.

**Comment by logicsandbox** [comment]
@AndreiMisiukevich 

#161 Added TabbedPage workaround to Readme

**Comment by rredoh** [comment]
Ahh.. Thanks then :)
I'll try it and tell the result soon
