### ISSUE TITLE
Every other image fails to load when this package is comined with FFImageLoading

### ISSUE THREAD

**Issue by jacob925** [AndreiMisiukevich/CardView#323]
this started happening fairly recently. all packages are up to date

I have a carouselView with a data template which contains an image. It does not matter if the image source is a binding or a literal value. 
With FFImageLoading enabled, every other image will fail to load/display. If I disable FFImageLoading, it works fine

All other images with FFImageLoading component work fine.

xaml:
```xaml
<cards:CarouselView x:Name="carousel"
                                VerticalOptions="Fill"
                                HorizontalOptions="Fill"
                                SlideShowDuration="4000"
                                ItemsSource="{Binding Pages}">
                <cards:CarouselView.ItemTemplate>
                    <DataTemplate>
                        <StackLayout Orientation="Vertical"
                                     VerticalOptions="Center"
                                     Spacing="0"
                                     Margin="0,0,0,0">
                            <Image Source="{Binding Image}"
                                   HeightRequest="160"
                                   VerticalOptions="End"
                                   HorizontalOptions="Center" />
                            <BoxView BackgroundColor="Transparent"
                                     HeightRequest="{Binding Source={x:Reference RefStartupPage}, Path=Spacing}" />
                            <Label LineBreakMode="WordWrap" BackgroundColor="Yellow"
                                   Text="{Binding Text}"
                                   Margin="73,0,73,0"
                                   FontSize="{StaticResource VeryLargeFontSize}"
                                   VerticalOptions="Start"
                                   HorizontalOptions="Center"
                                   HorizontalTextAlignment="Center" />
                            <Label LineBreakMode="WordWrap" BackgroundColor="Aqua"
                                   Text="{Binding SubText}"
                                   IsVisible="{Binding HasSubtext}"
                                   Margin="50,40,50,0"
                                   FontSize="{StaticResource FontSize}"
                                   VerticalOptions="Start"
                                   HorizontalOptions="Center"
                                   HorizontalTextAlignment="Center" />
                        </StackLayout>
                    </DataTemplate>
                </cards:CarouselView.ItemTemplate>
                <controls:IndicatorsControl SelectedIndicatorStyle="{StaticResource ActiveIndicator}"
                                            UnselectedIndicatorStyle="{StaticResource InactiveIndicator}" />
            </cards:CarouselView>
```

**Comment by AndreiMisiukevich** [comment]
Hi @jacob925 
Why did you decide this issue is related to CardsView?

CardsView knows nothing about the content (including FFImageLoading library).
So it does not matter what kind of data to show. And if something failing in "loading" images, CardsView is not the reason.

Also, I have samples which work pretty finew with FFImage https://github.com/AndreiMisiukevich/CardView/tree/master/PanCardViewSample


Do you get an error message in output? Perhaps image is loaded fine, but it has Height/Width = 0

**Comment by AndreiMisiukevich** [comment]
Is it iOS or Android?
Can you try previous version 2.3.9

I need more info or sample

**Comment by Pomezny** [comment]
@jacob925 I experienced similar problem recently after updating Xamarin Forms and CarouselView. It turned out, that using HorizontalOptions="Center" on Image was causing it to shrink and not to expand after image was loaded. Issue was little undeterministic, since in depended on which images managed to get loaded before UI was drawn and which did not. In my case changing HorizontalOptions and VerticalOptions to "FillAndExpand" solved the issue.

**Comment by AndreiMisiukevich** [comment]
@jacob925 try this workaround.
Or report the issue to FFImage project
