### ISSUE TITLE
Question: Changing opacity behavior for CardsView

### ISSUE THREAD

**Issue by robertmiles3** [AndreiMisiukevich/CardView#330]
First, thanks for the work! It's a great control.

I would like to change the behavior a bit such that when using CardsView, the card doesn't fade the opacity but instead just moves it off screen. Similar to this in Quizlet...

![Feb-05-2020 10-28-31](https://user-images.githubusercontent.com/944302/73820206-5287fe00-4802-11ea-9bc6-ef5d0a1c00c3.gif)

Would this be possible by altering the processor somehow?

**Comment by AndreiMisiukevich** [comment]
Hi @robertmiles3 
This is a good question. And yes, it's possible by writing custom processor

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Processors/BaseCardBackViewProcessor.cs
https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/Processors/BaseCardFrontViewProcessor.cs

Need to extend these two classes and write custom logic:
1) Remove all Opacity occurrences
2) Shift card outsides instead of fading

Feel free to ask questions
