### ISSUE TITLE
Animation for card leaving the screen is in the wrong direction on UWP.

### ISSUE THREAD

**Issue by rheesbeen** [AndreiMisiukevich/CardView#377]
When you move to the left (you go from say position 10 to 9) the animation for the card that is leaving animates/slides to the right. Expected behaviour is that it should animate/slide to the left.

Thnx for your time and please let me know how/when i can help.

**Comment by AndreiMisiukevich** [comment]
@rheesbeen hi. I am not sure I understood the problem.
Can you please record a video and attach the sample to show what is the issue?

**Comment by rheesbeen** [comment]
Here is the requested recording. Hopes this helps, if not let me know what I can do.

https://user-images.githubusercontent.com/34963849/114146473-e8904a80-9917-11eb-82cb-8d88432d3fa1.mp4

**Comment by AndreiMisiukevich** [comment]
@rheesbeen can you build a small sample app (And can you reproduce the same on Android or iOS, I guess you should be, cuz they use the same code base).

It's a weird behavior I have never seen before (cuz direction is determined based on two indices - Old and New)

Maybe, the problem is with your bottom "navigator"... So, I need a simple sample app that I can debug on Android or iOS (I believe the bug will be there as well).

**Comment by AndreiMisiukevich** [comment]
Basically, you can add IndicatorsControl to your carousel view. Then try to click indicators (they are clickable) and see if the issue exists.

**Comment by rheesbeen** [comment]
I will try it on Android and with your Indicatorcontro, but the navigator only changes the selectedindex (It also works with the xamarin forms carousel). I will let you know a.s.a.p.

**Comment by AndreiMisiukevich** [comment]
try 2.7.3

**Comment by rheesbeen** [comment]
YES! That fixes the issue. Thanks for your time.
